---
title: "2. SEC_R ImputationAndComputation"
output: html_document
---

library(RCurl)

x <- getURL("https://raw.githubusercontent.com/DallasNovakowski/Comparisons_Risk/master/SEC_R_Crowd_2_24_2019_Rcoded.csv")

tib_cleaning <- read.csv(text=x)


      

#imputing all items except demographics, and assigning these imputed datasets to unique objects
set.seed(111)
dat_na <- tib_cleaning[,c(VarBase$SSexp, VarBase$SSdis, VarBase$SSas, VarBase$SSbor, VarBase$BISa, VarBase$BISm, VarBase$BISn, VarBase$Dhea, VarBase$Dinv, VarBase$Dgam, VarBase$Deth, VarBase$Drec, VarBase$Dsoc, VarBase$SOEP, VarBase$Dm, VarBase$GBS, VarBase$NODS, VarBase$FTND, VarBase$DAST, VarBase$AUDIT, VarBase$SECtot)]


imputed <- mice(dat_na, m=20, maxit=10, meth='pmm', seed=500)

  	dat_imp1 <- mice::complete(imputed, 1)
	dat_imp2 <- mice::complete(imputed, 2)
	dat_imp3 <- mice::complete(imputed, 3)
	dat_imp4 <- mice::complete(imputed, 4)
	dat_imp5 <- mice::complete(imputed, 5)
	dat_imp6 <- mice::complete(imputed, 6)
	dat_imp7 <- mice::complete(imputed, 7)
	dat_imp8 <- mice::complete(imputed, 8)
	dat_imp9 <- mice::complete(imputed, 9)
	dat_imp10 <- mice::complete(imputed, 10)
	dat_imp11 <- mice::complete(imputed, 11)
	dat_imp12 <- mice::complete(imputed, 12)
	dat_imp13 <- mice::complete(imputed, 13)
	dat_imp14 <- mice::complete(imputed, 14)
	dat_imp15 <- mice::complete(imputed, 15)
	dat_imp16 <- mice::complete(imputed, 16)
	dat_imp17 <- mice::complete(imputed, 17)
	dat_imp18 <- mice::complete(imputed, 18)
	dat_imp19 <- mice::complete(imputed, 19)
	dat_imp20 <- mice::complete(imputed, 20)

#investigate logged events from imputation
imputed$loggedEvents

#Binding participant numbers to imputed data sets
dat_imp1 <- cbind.fill(dat_imp1,tib_cleaning[,c("Pnum")])
dat_imp2 <- cbind.fill(dat_imp2,tib_cleaning[,c("Pnum")])
dat_imp3 <- cbind.fill(dat_imp3,tib_cleaning[,c("Pnum")])
dat_imp4 <- cbind.fill(dat_imp4,tib_cleaning[,c("Pnum")])
dat_imp5 <- cbind.fill(dat_imp5,tib_cleaning[,c("Pnum")])
dat_imp6 <- cbind.fill(dat_imp6,tib_cleaning[,c("Pnum")])
dat_imp7 <- cbind.fill(dat_imp7,tib_cleaning[,c("Pnum")])
dat_imp8 <- cbind.fill(dat_imp8,tib_cleaning[,c("Pnum")])
dat_imp9 <- cbind.fill(dat_imp9,tib_cleaning[,c("Pnum")])
dat_imp10 <- cbind.fill(dat_imp10,tib_cleaning[,c("Pnum")])
dat_imp11 <- cbind.fill(dat_imp11,tib_cleaning[,c("Pnum")])
dat_imp12 <- cbind.fill(dat_imp12,tib_cleaning[,c("Pnum")])
dat_imp13 <- cbind.fill(dat_imp13,tib_cleaning[,c("Pnum")])
dat_imp14 <- cbind.fill(dat_imp14,tib_cleaning[,c("Pnum")])
dat_imp15 <- cbind.fill(dat_imp15,tib_cleaning[,c("Pnum")])
dat_imp16 <- cbind.fill(dat_imp16,tib_cleaning[,c("Pnum")])
dat_imp17 <- cbind.fill(dat_imp17,tib_cleaning[,c("Pnum")])
dat_imp18 <- cbind.fill(dat_imp18,tib_cleaning[,c("Pnum")])
dat_imp19 <- cbind.fill(dat_imp19,tib_cleaning[,c("Pnum")])
dat_imp20 <- cbind.fill(dat_imp20,tib_cleaning[,c("Pnum")])


#making summary imputed data set (taking mean from the 20 separate imputed data sets), then adding demographics
#NOTE: this isn't best practice, I should be running analyses for all 20 of these imputed datasets, then average the values of the parameter estimates to get a single point estimate. I DIDN'T do this because...
#there's also the question of whether I should have conducted imputations for summed scales/subscales or for the item-level indicators (I conducted the latter)
library(data.table)

tib_imputed <- rbindlist(list(dat_imp1, dat_imp2, dat_imp3, dat_imp4, dat_imp5, dat_imp6, dat_imp7, dat_imp8, dat_imp9, dat_imp10, dat_imp11, dat_imp12, dat_imp13, dat_imp14, dat_imp15, dat_imp16, dat_imp17, dat_imp18, dat_imp19, dat_imp20))[,lapply(.SD,mean), Pnum]

#drop NODS_15f because everyone answered "no"
tib_imputed <- dplyr::select (tib_imputed,-NODS_15f)

tib_filled <- cbind.fill(tib_imputed,tib_cleaning[,c(VarBase$demo)])

# VARIABLE COMPUTATION
SSexp <- rowSums(tib_filled[,c(VarBase$SSexp)])
SSdis <- rowSums(tib_filled[,c(VarBase$SSdis)])
SSas <- rowSums(tib_filled[,c(VarBase$SSas)])
SSbor <- rowSums(tib_filled[,c(VarBase$SSbor)])
BISa <- rowSums(tib_filled[,c(VarBase$BISa)])
BISm <- rowSums(tib_filled[,c(VarBase$BISm)])
BISn <- rowSums(tib_filled[,c(VarBase$BISn)])
Dhea <- rowSums(tib_filled[,c(VarBase$Dhea)])
Dinv <- rowSums(tib_filled[,c(VarBase$Dinv)])
Dgam <- rowSums(tib_filled[,c(VarBase$Dgam)])
Deth <- rowSums(tib_filled[,c(VarBase$Deth)])
Drec <- rowSums(tib_filled[,c(VarBase$Drec)])
Dsoc <- rowSums(tib_filled[,c(VarBase$Dsoc)])
Dm <- rowSums(tib_filled[,c(VarBase$Dm)])
GBS <- rowSums(tib_filled[,c(VarBase$GBS)])
DAST <- rowSums(tib_filled[,c(VarBase$DAST)])
FTND <- rowSums(tib_filled[,c(VarBase$FTND)])
AUDIT <- rowSums(tib_filled[,c(VarBase$AUDIT)])
NODS <- rowSums(tib_filled[,c(VarBase$NODS)])
SECtot <- rowSums(tib_filled[,c(VarBase$SECtot)])
SECenvy <- rowSums(tib_filled[,c(VarBase$SECenvy)])
SECcse <- rowSums(tib_filled[,c(VarBase$SECcse)])
SECjs <- rowSums(tib_filled[,c(VarBase$SECjs)])

#all variables that are the result of a summation process
VarBase$Summed <- c('SSexp', 'SSdis', 'SSas', 'SSbor', 'BISa', 'BISm', 'BISn', 'Dhea', 'Dinv', 'Dgam', 'Deth', 'Drec', 'Dsoc', 'Dm', 'GBS', 'DAST', 'FTND', 'AUDIT', 'NODS', 'SECenvy', 'SECcse', 'SECjs')

#all variables that are needed for model specification
#VarBase$Demo, VarBase$Pnum
VarBase$Spec <- c('SSexp', 'SSdis', 'SSas', 'SSbor', 'BISa', 'BISm', 'BISn', 'Dhea', 'Dinv', 'Dgam', 'Deth', 'Drec', 'Dsoc', 'Dm', 'GBS', 'DAST', 'FTND', 'AUDIT', 'NODS','SEC_1', 'SEC_2', 'SEC_3', 'SEC_4', 'SEC_5', 'SEC_6', 'SEC_7', 'SEC_8', 'SEC_9', 'SEC_10', 'SEC_11', 'SEC_12')
VarBase$R <- c('SSexp', 'SSdis', 'SSas', 'SSbor', 'BISa', 'BISm', 'BISn', 'Dhea', 'Dinv', 'Dgam', 'Deth', 'Drec', 'Dsoc', 'Dm', 'GBS', 'DAST', 'FTND', 'AUDIT', 'NODS')

#adding computed variables to new dataset
tib_summed <- cbind(tib_filled, SSexp, SSdis, SSas, SSbor, BISa, BISm, BISn, Dhea, Dinv, Dgam, Deth, Drec, Dsoc, Dm, GBS, DAST, FTND, AUDIT, NODS, SECenvy, SECcse, SECjs)

# find DVs that are numeric / ordered factors, which can be converted / scaled
DVs <- NULL
for (i in 1:ncol(tib_summed)) {
  if (is.numeric(tib_summed[,i])) DVs <- c(DVs, names(tib_summed[i]))
  if (is.ordered(tib_summed[,i])) DVs <- c(DVs, names(tib_summed[i]))
}

tib_complete <- tib_summed[complete.cases(tib_summed),]


# create objects with standardized variables / residuals after controlling for age, sex,
tib_std <- tib_complete
tib_std[] <- NA

residuals <- tib_complete
residuals[] <- NA
residuals_num <- residuals
residuals_std <- residuals
residuals_std2 <- residuals

models <- list()
for (DV in DVs) {
  print(DV)
  curr_raw <- tib_complete[,DV]

 # convert measures to numeric
  if (is.numeric(curr_raw)) curr_raw_num <- curr_raw
  else curr_raw_num <- as.numeric(as.character(curr_raw))

  # standardize measures
  tib_std[,DV] <- scale(tib_complete[,DV])

 # get residuals (but not for "age")
# VarBase$Demo, VarBase$Pnum (tib_complete[,c(VarBase$Spec)])
  if (DV != "age" & DV != "Pnum" & DV != "sex") {
	formula <- as.formula(paste(DV, "~ 1 + age + sex"))


    if (is.numeric(curr_raw)) {
      p_col <- "grey"
      ind_ok <- which(!is.na(tib_complete[,DV]))
      mod.gauss <- lm(formula, data=tib_complete)
      models[[DV]] <- mod.gauss
      pred <- predict(mod.gauss, newdata=tib_complete[ind_ok,])
      residuals[ind_ok,DV] <- tib_complete[ind_ok,DV] - pred
      residuals_num[,DV] <- residuals[,DV]
      residuals_std[,DV] <- as.numeric(scale(residuals_num[,DV]))
      residuals_std2[,DV] <- as.numeric(scale(residuals_num[,DV]))
    } else {
      p_col <- "red"
      ind_ok <- which(!is.na(tib_complete[,DV]))
      mod.ord <- clm(formula, data=tib_complete)
      models[[DV]] <- mod.ord
      pred <- as.numeric(as.character(predict(mod.ord, type="class", newdata=tib_complete[ind_ok,])$fit))
      residuals[ind_ok,DV] <- tib_num[ind_ok,DV] - pred
      residuals[,DV] <- as.ordered(residuals[,DV])
      residuals_num[,DV] <- as.numeric(as.character(residuals[,DV]))
      residuals_std[,DV] <- residuals[,DV]
      residuals_std2[,DV] <- as.numeric(scale(residuals_num[,DV]))
    }


  }
}

residuals[,c("age", "Pnum", "sex", "Pincome","Hincome")] <- tib_complete[,c("age", "Pnum", "sex", "Pincome","Hincome")]
residuals_num[,c("age", "Pnum", "sex", "Pincome","Hincome")] <- tib_complete[,c("age", "Pnum", "sex", "Pincome","Hincome")]
residuals_std[,c("age", "Pnum", "sex", "Pincome","Hincome")] <- tib_complete[,c("age", "Pnum", "sex", "Pincome","Hincome")]
residuals_std2[,c("age", "Pnum", "sex", "Pincome","Hincome")] <- tib_complete[,c("age", "Pnum", "sex", "Pincome","Hincome")]


save(tib_summed, tib_complete, tib_std, tib_filled, tib_cleaning, tib_imputed, VarBase, residuals,residuals_num,residuals_std,residuals_std2, file="C:/Users/dalla/Google Drive/R Coding/Comparisons_Risk/SEC_R_Crowd_2_22_2019_imputed.Rdata")

save(dat_imp1, dat_imp2, dat_imp3, dat_imp4, dat_imp5, dat_imp6, dat_imp7, dat_imp8, dat_imp9, dat_imp10, dat_imp11, dat_imp12, dat_imp13, dat_imp14, dat_imp15, dat_imp16, dat_imp17, dat_imp18, dat_imp19, dat_imp20, tib_cleaning, tib_imputed, VarBase, file="C:/Users/dalla/Google Drive/R Coding/Comparisons_Risk/SEC_R_Crowd_2_22_2019_imputations.Rdata")

write.csv(tib_summed, file="C:/Users/dalla/Google Drive/R Coding/Comparisons_Risk/SEC_R_Crowd_2_22_2019_cleaned&imputed.csv")