---
title: "DataCleaning"
output: html_document
---

#readr for reading csv files as tibble
#stargazer for tables
#car for reverse coding
#psych for internal consistency
#VIM for missing data graphs
#mice for missing data imputation and exploration
#summarytools for missing data, histograms, mean, and SD
#}

#Clear memory
rm(list=ls())
#}

#load libraries and data {
library(stargazer)
library (car)
library(summarytools)
library(VIM)
library (psych)
library (mice)
library(tidyverse)
library(readr)
library(rowr)
library(lavaan)

#Load data, assign to tibble
tib_identified <- read_csv(file = "C:/Users/dalla/Google Drive/CURRENT/SEC_R_SGISaskGaming/SEC_R_crowdsourced/SEC_R_Study_CrowdSourced_February 4, 2019_15.08_numeric.csv")
#}

names(tib_identified)[names(tib_identified)=="Duration (in seconds)"] <- "Duration"
names(tib_identified)[names(tib_identified)=="Recorded Date"] <- "RecordedDate"


tib <- dplyr::select (tib_identified, -c(StartDate, EndDate, Status, IPAddress, Progress, Duration, Finished, RecordedDate, ResponseId, RecipientLastName, RecipientFirstName, RecipientEmail, ExternalReference, LocationLatitude, LocationLongitude, DistributionChannel, UserLanguage, ResultsEmail))

names(tib)[names(tib)=="pincome"] <- "Pincome"

write.csv(tib, file="C:/Users/dalla/Google Drive/R Coding/SEC_R Crowdsourced/SEC_R_Crowd_2_24_2019_anonymized.csv")


#reverse coding for impulsivity and sensation-seeking scales
tib$BIS_6r <- as.numeric(dplyr::recode(tib$BIS_6, "1" = "4" , "3" = "2" , "4" = "1" , "2" = "3"))
tib$BIS_7r <- as.numeric(dplyr::recode(tib$BIS_7, "1" = "4" , "3" = "2" , "4" = "1" , "2" = "3"))
tib$BIS_8r <- as.numeric(dplyr::recode(tib$BIS_8, "1" = "4" , "3" = "2" , "4" = "1" , "2" = "3"))
tib$BIS_9r <- as.numeric(dplyr::recode(tib$BIS_9, "1" = "4" , "3" = "2" , "4" = "1" , "2" = "3"))
tib$BIS_10r <- as.numeric(dplyr::recode(tib$BIS_10, "1" = "4" , "3" = "2" , "4" = "1" , "2" = "3"))
tib$BIS_13r <- as.numeric(dplyr::recode(tib$BIS_13, "1" = "4" , "3" = "2" , "4" = "1" , "2" = "3"))


tib$BSCS_2r <- as.numeric(dplyr::recode(tib$BSCS_2, "1" = "5" , "2" = "4" , "3" = "3" , "4" = "2" , "5" = "1"))
tib$BSCS_3r <- as.numeric(dplyr::recode(tib$BSCS_3, "1" = "5" , "2" = "4" , "3" = "3" , "4" = "2" , "5" = "1"))
tib$BSCS_4r <- as.numeric(dplyr::recode(tib$BSCS_4, "1" = "5" , "2" = "4" , "3" = "3" , "4" = "2" , "5" = "1"))
tib$BSCS_5r <- as.numeric(dplyr::recode(tib$BSCS_5, "1" = "5" , "2" = "4" , "3" = "3" , "4" = "2" , "5" = "1"))
tib$BSCS_7r <- as.numeric(dplyr::recode(tib$BSCS_7, "1" = "5" , "2" = "4" , "3" = "3" , "4" = "2" , "5" = "1"))
tib$BSCS_9r <- as.numeric(dplyr::recode(tib$BSCS_9, "1" = "5" , "2" = "4" , "3" = "3" , "4" = "2" , "5" = "1"))
tib$BSCS_10r <- as.numeric(dplyr::recode(tib$BSCS_10, "1" = "5" , "2" = "4" , "3" = "3" , "4" = "2" , "5" = "1"))
tib$BSCS_12r <- as.numeric(dplyr::recode(tib$BSCS_12, "1" = "5" , "2" = "4" , "3" = "3" , "4" = "2" , "5" = "1"))
tib$BSCS_13r <- as.numeric(dplyr::recode(tib$BSCS_13, "1" = "5" , "2" = "4" , "3" = "3" , "4" = "2" , "5" = "1"))




#recoding FTND measures because they're skewed by +1
tib$FTND_1f <- tib$FTND_1 -1 
tib$FTND_2f <- tib$FTND_2 -1 
tib$FTND_3f <- tib$FTND_3 -1 
tib$FTND_4f <- tib$FTND_4 -1 
tib$FTND_5f <- tib$FTND_5 -1 
tib$FTND_6f <- tib$FTND_6 -1 

#recoding NODS measures so that 1(yes)=1 and 2(no)=0 
tib$NODS_1f <- as.numeric(dplyr::recode(tib$NODS_1, "1" = "1" , "2" = "0"))
tib$NODS_2f <- as.numeric(dplyr::recode(tib$NODS_2, "1" = "1" , "2" = "0"))
tib$NODS_3f <- as.numeric(dplyr::recode(tib$NODS_3, "1" = "1" , "2" = "0"))
tib$NODS_4f <- as.numeric(dplyr::recode(tib$NODS_4, "1" = "1" , "2" = "0"))
tib$NODS_5f <- as.numeric(dplyr::recode(tib$NODS_5, "1" = "1" , "2" = "0"))
tib$NODS_6f <- as.numeric(dplyr::recode(tib$NODS_6, "1" = "1" , "2" = "0"))
tib$NODS_7f <- as.numeric(dplyr::recode(tib$NODS_7, "1" = "1" , "2" = "0"))
tib$NODS_8f <- as.numeric(dplyr::recode(tib$NODS_8, "1" = "1" , "2" = "0"))
tib$NODS_9f <- as.numeric(dplyr::recode(tib$NODS_9, "1" = "1" , "2" = "0"))
tib$NODS_10f <- as.numeric(dplyr::recode(tib$NODS_10, "1" = "1" , "2" = "0"))
tib$NODS_11f <- as.numeric(dplyr::recode(tib$NODS_11, "1" = "1" , "2" = "0"))
tib$NODS_12f <- as.numeric(dplyr::recode(tib$NODS_12, "1" = "1" , "2" = "0"))
tib$NODS_13f <- as.numeric(dplyr::recode(tib$NODS_13, "1" = "1" , "2" = "0"))
tib$NODS_14f <- as.numeric(dplyr::recode(tib$NODS_14, "1" = "1" , "2" = "0"))
tib$NODS_15f <- as.numeric(dplyr::recode(tib$NODS_15, "1" = "1" , "2" = "0"))
tib$NODS_16f <- as.numeric(dplyr::recode(tib$NODS_16, "1" = "1" , "2" = "0"))
tib$NODS_17f <- as.numeric(dplyr::recode(tib$NODS_17, "1" = "1" , "2" = "0"))

#recoding DAST measures so that 1(yes)=1 and 2(no)=0 (and reverse-code DAST_3f)
tib$DAST_1f <- as.numeric(dplyr::recode(tib$DAST_1, "1" = "1" , "2" = "0"))
tib$DAST_2f <- as.numeric(dplyr::recode(tib$DAST_2, "1" = "1" , "2" = "0"))
tib$DAST_3f <- as.numeric(dplyr::recode(tib$DAST_3, "1" = "1" , "2" = "0"))
tib$DAST_3fr <- as.numeric(dplyr::recode(tib$DAST_3f, "1" = "0" , "0" = "1"))
tib$DAST_4f <- as.numeric(dplyr::recode(tib$DAST_4, "1" = "1" , "2" = "0"))
tib$DAST_5f <- as.numeric(dplyr::recode(tib$DAST_5, "1" = "1" , "2" = "0"))
tib$DAST_6f <- as.numeric(dplyr::recode(tib$DAST_6, "1" = "1" , "2" = "0"))
tib$DAST_7f <- as.numeric(dplyr::recode(tib$DAST_7, "1" = "1" , "2" = "0"))
tib$DAST_8f <- as.numeric(dplyr::recode(tib$DAST_8, "1" = "1" , "2" = "0"))
tib$DAST_9f <- as.numeric(dplyr::recode(tib$DAST_9, "1" = "1" , "2" = "0"))
tib$DAST_10f <- as.numeric(dplyr::recode(tib$DAST_10, "1" = "1" , "2" = "0"))

#create lists for variable computation
VarBase <- list()
VarBase$Pnum <- c('Pnum', 'AttnChckPass')
VarBase$demo <-  c('age', 'sex', 'Pincome', 'Hincome', 'Smoke_YN')
VarBase$SSexp <-  c('SS_1', 'SS_5')
VarBase$SSdis <-  c('SS_4', 'SS_8')
VarBase$SSas <-  c('SS_3', 'SS_7')
VarBase$SSbor <-  c('SS_2', 'SS_6')
VarBase$BISa <-  c('BIS_11', 'BIS_12', 'BIS_13r', 'BIS_14', 'BIS_15')
VarBase$BISm <-  c('BIS_1', 'BIS_2', 'BIS_3', 'BIS_4', 'BIS_5')
VarBase$BISn <-  c('BIS_6r', 'BIS_7r', 'BIS_8r', 'BIS_9r', 'BIS_10r')
VarBase$Dhea <-  c('DsrA_5', 'DsrA_15', 'DsrA_17', 'DsrA_20', 'DsrA_23', 'DsrA_26')
VarBase$Dinv <-  c('DsrA_4', 'DsrA_12', 'DsrA_18')
VarBase$Dgam <-  c('DsrA_3', 'DsrA_8', 'DsrA_14')
VarBase$Deth <-  c('DsrA_6', 'DsrA_9', 'DsrA_10', 'DsrA_16', 'DsrA_29', 'DsrA_30')
VarBase$Drec <-  c('DsrA_2', 'DsrA_11', 'DsrA_13', 'DsrA_19', 'DsrA_24', 'DsrA_25')
VarBase$Dsoc <-  c('DsrA_1', 'DsrA_7', 'DsrA_21', 'DsrA_22', 'DsrA_27', 'DsrA_28')
VarBase$SOEP <-  c('SOEPg', 'SOEPdri', 'SOEPocc', 'SOEPfin', 'SOEPrec', 'SOEPhea', 'SOEPsoc')
VarBase$Dm <-  c('Dm_1', 'Dm_2', 'Dm_3', 'Dm_4', 'Dm_5', 'Dm_6', 'Dm_7', 'Dm_8', 'Dm_9', 'Dm_10', 'Dm_11', 'Dm_12', 'Dm_13', 'Dm_14', 'Dm_15', 'Dm_16', 'Dm_17', 'Dm_18', 'Dm_19')
VarBase$GBS <-  c('GBS_lott', 'GBS_raf', 'GBS_scrat', 'GBS_bing', 'GBS_vlt', 'GBS_table', 'GBS_sport', 'GBS_horse', 'GBS_skill', 'GBS_stock')
VarBase$GBS_all <-  c('GBS_lott', 'GBS_raf', 'GBS_scrat', 'GBS_bing', 'GBS_vlt', 'GBS_table', 'GBS_sport', 'GBS_horse', 'GBS_skill', 'GBS_stock', 'GBS_oth1', 'GBS_oth2')
VarBase$DASTb <-  c('DAST_1', 'DAST_2', 'DAST_3', 'DAST_4', 'DAST_5', 'DAST_6', 'DAST_7', 'DAST_8', 'DAST_9', 'DAST_10')
VarBase$DAST <-  c('DAST_1f', 'DAST_2f', 'DAST_3fr', 'DAST_4f', 'DAST_5f', 'DAST_6f', 'DAST_7f', 'DAST_8f', 'DAST_9f', 'DAST_10f')
VarBase$FTND <-  c('FTND_1f', 'FTND_2f', 'FTND_3f', 'FTND_4f', 'FTND_5f', 'FTND_6f')
VarBase$AUDIT <-  c('AUDIT_1', 'AUDIT_2', 'AUDIT_3', 'AUDIT_4', 'AUDIT_5', 'AUDIT_6', 'AUDIT_7', 'AUDIT_8', 'AUDIT_9', 'AUDIT_10')
VarBase$NODS <-  c('NODS_1f', 'NODS_2f', 'NODS_3f', 'NODS_4f', 'NODS_5f', 'NODS_6f', 'NODS_7f', 'NODS_8f', 'NODS_9f', 'NODS_10f', 'NODS_11f', 'NODS_12f', 'NODS_13f', 'NODS_14f', 'NODS_16f', 'NODS_17f')
#pipe = only presented if condition met; 7: if unsuccessful cessation attempted, 12: if lied to social network, 15: only if in school
VarBase$NODSpipe <- c('NODS_7f', 'NODS_12f','NODS_15f')
VarBase$SECtot <-  c('SEC_1', 'SEC_2', 'SEC_3', 'SEC_4', 'SEC_5', 'SEC_6', 'SEC_7', 'SEC_8', 'SEC_9', 'SEC_10', 'SEC_11', 'SEC_12')
VarBase$SECenvy <-  c('SEC_1', 'SEC_2', 'SEC_3', 'SEC_4')
VarBase$SECcse <-  c('SEC_5', 'SEC_6','SEC_7', 'SEC_8')
VarBase$SECjs <- c('SEC_9','SEC_10', 'SEC_11', 'SEC_12')

VarBase$ALL <- c(VarBase$SSexp, VarBase$SSdis, VarBase$SSas, VarBase$SSbor, VarBase$BISa, VarBase$BISm, VarBase$BISn, VarBase$Dhea, VarBase$Dinv, VarBase$Dgam, VarBase$Deth, VarBase$Drec, VarBase$Dsoc, VarBase$SOEP, VarBase$Dm, VarBase$GBS, VarBase$NODS, VarBase$DAST, VarBase$AUDIT, VarBase$SECtot)

# Recode NODS_7, NODS_12, NODS_15 so that NA = 0 (piped items that are skipped with "no" responses)
tib[,c(VarBase$NODSpipe)][is.na(tib[,c(VarBase$NODSpipe)])] <- 0

#create cleaning datasets, only including those participants that passed the attention check
tib_cleaning <- filter(tib, tib$AttnChckPass == 1)
tib_imputed <- filter(tib, tib$AttnChckPass == 1)

#Give nonsmokers 0 scores on all FTND items
tib_cleaning[,c(VarBase$FTND)][tib_cleaning$Smoke_YN == 2 & is.na(tib_cleaning[,c(VarBase$FTND)])] <- 0
tib_imputed[,c(VarBase$FTND)][tib_imputed$Smoke_YN == 2 & is.na(tib_imputed[,c(VarBase$FTND)])] <- 0

# remove Pnums 91, 606, and 606 due to excessive missing data
tib_cleaning <- tib_cleaning[tib_cleaning$Pnum!=91 & tib_cleaning$Pnum!=966 & tib_cleaning$Pnum!=606, ]


save(tib_cleaning, file="C:/Users/dalla/Google Drive/CURRENT/SEC_R_SGISaskGaming/SEC_R_crowdsourced/SEC_R_Crowd_2_4_2019_Rcoded.csv")


#imputing all items except demographics, and assigning these imputed datasets to unique objects
set.seed(111)
dat_na <- tib_cleaning[,c(VarBase$SSexp, VarBase$SSdis, VarBase$SSas, VarBase$SSbor, VarBase$BISa, VarBase$BISm, VarBase$BISn, VarBase$Dhea, VarBase$Dinv, VarBase$Dgam, VarBase$Deth, VarBase$Drec, VarBase$Dsoc, VarBase$SOEP, VarBase$Dm, VarBase$GBS, VarBase$NODS, VarBase$FTND, VarBase$DAST, VarBase$AUDIT, VarBase$SECtot)]


imputed <- mice(dat_na, m=20, maxit=10, meth='pmm', seed=500)

  	dat_imp1 <- mice::complete(imputed, 1)
	dat_imp2 <- mice::complete(imputed, 2)
	dat_imp3 <- mice::complete(imputed, 3)
	dat_imp4 <- mice::complete(imputed, 4)
	dat_imp5 <- mice::complete(imputed, 5)
	dat_imp6 <- mice::complete(imputed, 6)
	dat_imp7 <- mice::complete(imputed, 7)
	dat_imp8 <- mice::complete(imputed, 8)
	dat_imp9 <- mice::complete(imputed, 9)
	dat_imp10 <- mice::complete(imputed, 10)
	dat_imp11 <- mice::complete(imputed, 11)
	dat_imp12 <- mice::complete(imputed, 12)
	dat_imp13 <- mice::complete(imputed, 13)
	dat_imp14 <- mice::complete(imputed, 14)
	dat_imp15 <- mice::complete(imputed, 15)
	dat_imp16 <- mice::complete(imputed, 16)
	dat_imp17 <- mice::complete(imputed, 17)
	dat_imp18 <- mice::complete(imputed, 18)
	dat_imp19 <- mice::complete(imputed, 19)
	dat_imp20 <- mice::complete(imputed, 20)

#investigate logged events from imputation
imputed$loggedEvents

#Binding participant numbers to imputed data sets
dat_imp1 <- cbind.fill(dat_imp1,tib_cleaning[,c("Pnum")])
dat_imp2 <- cbind.fill(dat_imp2,tib_cleaning[,c("Pnum")])
dat_imp3 <- cbind.fill(dat_imp3,tib_cleaning[,c("Pnum")])
dat_imp4 <- cbind.fill(dat_imp4,tib_cleaning[,c("Pnum")])
dat_imp5 <- cbind.fill(dat_imp5,tib_cleaning[,c("Pnum")])
dat_imp6 <- cbind.fill(dat_imp6,tib_cleaning[,c("Pnum")])
dat_imp7 <- cbind.fill(dat_imp7,tib_cleaning[,c("Pnum")])
dat_imp8 <- cbind.fill(dat_imp8,tib_cleaning[,c("Pnum")])
dat_imp9 <- cbind.fill(dat_imp9,tib_cleaning[,c("Pnum")])
dat_imp10 <- cbind.fill(dat_imp10,tib_cleaning[,c("Pnum")])
dat_imp11 <- cbind.fill(dat_imp11,tib_cleaning[,c("Pnum")])
dat_imp12 <- cbind.fill(dat_imp12,tib_cleaning[,c("Pnum")])
dat_imp13 <- cbind.fill(dat_imp13,tib_cleaning[,c("Pnum")])
dat_imp14 <- cbind.fill(dat_imp14,tib_cleaning[,c("Pnum")])
dat_imp15 <- cbind.fill(dat_imp15,tib_cleaning[,c("Pnum")])
dat_imp16 <- cbind.fill(dat_imp16,tib_cleaning[,c("Pnum")])
dat_imp17 <- cbind.fill(dat_imp17,tib_cleaning[,c("Pnum")])
dat_imp18 <- cbind.fill(dat_imp18,tib_cleaning[,c("Pnum")])
dat_imp19 <- cbind.fill(dat_imp19,tib_cleaning[,c("Pnum")])
dat_imp20 <- cbind.fill(dat_imp20,tib_cleaning[,c("Pnum")])


#making summary imputed data set (taking mean from the 20 separate imputed data sets), then adding demographics
#NOTE: this isn't best practice, I should be running analyses for all 20 of these imputed datasets, then average the values of the parameter estimates to get a single point estimate. I DIDN'T do this because...
#there's also the question of whether I should have conducted imputations for summed scales/subscales or for the item-level indicators (I conducted the latter)
library(data.table)

tib_imputed <- rbindlist(list(dat_imp1, dat_imp2, dat_imp3, dat_imp4, dat_imp5, dat_imp6, dat_imp7, dat_imp8, dat_imp9, dat_imp10, dat_imp11, dat_imp12, dat_imp13, dat_imp14, dat_imp15, dat_imp16, dat_imp17, dat_imp18, dat_imp19, dat_imp20))[,lapply(.SD,mean), Pnum]

#drop NODS_15f because everyone answered "no"
tib_imputed <- dplyr::select (tib_imputed,-NODS_15f)

tib_filled <- cbind.fill(tib_imputed,tib_cleaning[,c(VarBase$demo)])

# VARIABLE COMPUTATION
SSexp <- rowSums(tib_filled[,c(VarBase$SSexp)])
SSdis <- rowSums(tib_filled[,c(VarBase$SSdis)])
SSas <- rowSums(tib_filled[,c(VarBase$SSas)])
SSbor <- rowSums(tib_filled[,c(VarBase$SSbor)])
BISa <- rowSums(tib_filled[,c(VarBase$BISa)])
BISm <- rowSums(tib_filled[,c(VarBase$BISm)])
BISn <- rowSums(tib_filled[,c(VarBase$BISn)])
Dhea <- rowSums(tib_filled[,c(VarBase$Dhea)])
Dinv <- rowSums(tib_filled[,c(VarBase$Dinv)])
Dgam <- rowSums(tib_filled[,c(VarBase$Dgam)])
Deth <- rowSums(tib_filled[,c(VarBase$Deth)])
Drec <- rowSums(tib_filled[,c(VarBase$Drec)])
Dsoc <- rowSums(tib_filled[,c(VarBase$Dsoc)])
Dm <- rowSums(tib_filled[,c(VarBase$Dm)])
GBS <- rowSums(tib_filled[,c(VarBase$GBS)])
DAST <- rowSums(tib_filled[,c(VarBase$DAST)])
FTND <- rowSums(tib_filled[,c(VarBase$FTND)])
AUDIT <- rowSums(tib_filled[,c(VarBase$AUDIT)])
NODS <- rowSums(tib_filled[,c(VarBase$NODS)])
SECtot <- rowSums(tib_filled[,c(VarBase$SECtot)])
SECenvy <- rowSums(tib_filled[,c(VarBase$SECenvy)])
SECcse <- rowSums(tib_filled[,c(VarBase$SECcse)])
SECjs <- rowSums(tib_filled[,c(VarBase$SECjs)])

#all variables that are the result of a summation process
VarBase$Summed <- c('SSexp', 'SSdis', 'SSas', 'SSbor', 'BISa', 'BISm', 'BISn', 'Dhea', 'Dinv', 'Dgam', 'Deth', 'Drec', 'Dsoc', 'Dm', 'GBS', 'DAST', 'FTND', 'AUDIT', 'NODS', 'SECenvy', 'SECcse', 'SECjs')

#all variables that are needed for model specification
#VarBase$Demo, VarBase$Pnum
VarBase$Spec <- c('SSexp', 'SSdis', 'SSas', 'SSbor', 'BISa', 'BISm', 'BISn', 'Dhea', 'Dinv', 'Dgam', 'Deth', 'Drec', 'Dsoc', 'Dm', 'GBS', 'DAST', 'FTND', 'AUDIT', 'NODS','SEC_1', 'SEC_2', 'SEC_3', 'SEC_4', 'SEC_5', 'SEC_6', 'SEC_7', 'SEC_8', 'SEC_9', 'SEC_10', 'SEC_11', 'SEC_12')
VarBase$R <- c('SSexp', 'SSdis', 'SSas', 'SSbor', 'BISa', 'BISm', 'BISn', 'Dhea', 'Dinv', 'Dgam', 'Deth', 'Drec', 'Dsoc', 'Dm', 'GBS', 'DAST', 'FTND', 'AUDIT', 'NODS')

#adding computed variables to new dataset
tib_summed <- cbind(tib_filled, SSexp, SSdis, SSas, SSbor, BISa, BISm, BISn, Dhea, Dinv, Dgam, Deth, Drec, Dsoc, Dm, GBS, DAST, FTND, AUDIT, NODS, SECenvy, SECcse, SECjs)

# find DVs that are numeric / ordered factors, which can be converted / scaled
DVs <- NULL
for (i in 1:ncol(tib_summed)) {
  if (is.numeric(tib_summed[,i])) DVs <- c(DVs, names(tib_summed[i]))
  if (is.ordered(tib_summed[,i])) DVs <- c(DVs, names(tib_summed[i]))
}

tib_complete <- tib_summed[complete.cases(tib_summed),]


# create objects with standardized variables / residuals after controlling for age, sex,
tib_std <- tib_complete
tib_std[] <- NA

residuals <- tib_complete
residuals[] <- NA
residuals_num <- residuals
residuals_std <- residuals
residuals_std2 <- residuals

models <- list()
for (DV in DVs) {
  print(DV)
  curr_raw <- tib_complete[,DV]

 # convert measures to numeric
  if (is.numeric(curr_raw)) curr_raw_num <- curr_raw
  else curr_raw_num <- as.numeric(as.character(curr_raw))

  # standardize measures
  tib_std[,DV] <- scale(tib_complete[,DV])

 # get residuals (but not for "age")
# VarBase$Demo, VarBase$Pnum (tib_complete[,c(VarBase$Spec)])
  if (DV != "age" & DV != "Pnum" & DV != "sex") {
	formula <- as.formula(paste(DV, "~ 1 + age + sex"))


    if (is.numeric(curr_raw)) {
      p_col <- "grey"
      ind_ok <- which(!is.na(tib_complete[,DV]))
      mod.gauss <- lm(formula, data=tib_complete)
      models[[DV]] <- mod.gauss
      pred <- predict(mod.gauss, newdata=tib_complete[ind_ok,])
      residuals[ind_ok,DV] <- tib_complete[ind_ok,DV] - pred
      residuals_num[,DV] <- residuals[,DV]
      residuals_std[,DV] <- as.numeric(scale(residuals_num[,DV]))
      residuals_std2[,DV] <- as.numeric(scale(residuals_num[,DV]))
    } else {
      p_col <- "red"
      ind_ok <- which(!is.na(tib_complete[,DV]))
      mod.ord <- clm(formula, data=tib_complete)
      models[[DV]] <- mod.ord
      pred <- as.numeric(as.character(predict(mod.ord, type="class", newdata=tib_complete[ind_ok,])$fit))
      residuals[ind_ok,DV] <- tib_num[ind_ok,DV] - pred
      residuals[,DV] <- as.ordered(residuals[,DV])
      residuals_num[,DV] <- as.numeric(as.character(residuals[,DV]))
      residuals_std[,DV] <- residuals[,DV]
      residuals_std2[,DV] <- as.numeric(scale(residuals_num[,DV]))
    }


  }
}

residuals[,c("age", "Pnum", "sex", "Pincome","Hincome")] <- tib_complete[,c("age", "Pnum", "sex", "Pincome","Hincome")]
residuals_num[,c("age", "Pnum", "sex", "Pincome","Hincome")] <- tib_complete[,c("age", "Pnum", "sex", "Pincome","Hincome")]
residuals_std[,c("age", "Pnum", "sex", "Pincome","Hincome")] <- tib_complete[,c("age", "Pnum", "sex", "Pincome","Hincome")]
residuals_std2[,c("age", "Pnum", "sex", "Pincome","Hincome")] <- tib_complete[,c("age", "Pnum", "sex", "Pincome","Hincome")]


save(tib_summed, tib_complete, tib_std, tib_filled, tib_cleaning, tib_imputed, VarBase, residuals,residuals_num,residuals_std,residuals_std2, file="C:/Users/dalla/Google Drive/CURRENT/SEC_R_SGISaskGaming/SEC_R_crowdsourced/SEC_R_Crowd_2_22_2019_imputed.Rdata")

save(dat_imp1, dat_imp2, dat_imp3, dat_imp4, dat_imp5, dat_imp6, dat_imp7, dat_imp8, dat_imp9, dat_imp10, dat_imp11, dat_imp12, dat_imp13, dat_imp14, dat_imp15, dat_imp16, dat_imp17, dat_imp18, dat_imp19, dat_imp20, tib_cleaning, tib_imputed, VarBase, file="C:/Users/dalla/Google Drive/CURRENT/SEC_R_SGISaskGaming/SEC_R_crowdsourced/SEC_R_Crowd_2_22_2019_imputations.Rdata")

write.csv(tib_summed, file="C:/Users/dalla/Google Drive/CURRENT/SEC_R_SGISaskGaming/SEC_R_crowdsourced/SEC_R_Crowd_2_22_2019_cleaned&imputed.csv")